### ISSUE TITLE
Querying for more than 30 results

### ISSUE THREAD

**Issue by dominictwlee** [emidev98/token-snapshot#2]
So i've looked into the code and tried changing the query limit to something higher for CW721, but it still caps at 30. Do you know why that is? Any help would be much appreciated!

**Comment by emidev98** [comment]
Hey, it is because CW20 has an hardcoded limitation of [30 maximum positions that can be returned](https://github.com/CosmWasm/cw-plus/blob/main/contracts/cw20-base/src/enumerable.rs#L11-L12). 

If you need to speed-up the process of requesting data faster you could use a snapshot or host your own node
